# Generated by Django 5.1.4 on 2024-12-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_spec', models.CharField(max_length=100)),
                ('trainer_image', models.ImageField(upload_to='trainer_images')),
                ('workout_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout')),
            ],
        ),
    ]
